config/routes.rb
Rails.application.routes.draw do

  get "home/about" => "homes#show"
  root to: 'homes#index'
  devise_for :users
<<<<<<< HEAD
  resources :users, only:[:show, :edit, :update, :index] do
    get 'following' => 'relationships#following'
    get 'followed' => 'relationships#followed'
  end



  resources :books do
  	resource :favorites, only:[:create, :destroy]
  	resources :book_comments, only:[:create, :destroy]
  end

  resources :relationships, only:[:create, :destroy]

  get '/search' => 'searches#search'
=======
  resources :books
  resources :users, only:[:show, :edit, :update, :index]
>>>>>>> origin/master
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
<<<<<<< HEAD
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
=======
>>>>>>> origin/master
  attachment :profile_image

  validates :name, presence: true
  validates :name, length:{maximum:20}
  validates :name, length:{minimum:2}
  validates :introduction, length:{maximum:50}

<<<<<<< HEAD
  has_many :relationships, foreign_key: 'user_id'
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user) #フォローしているuserを持ってきてother_userがいないか確認
  end



  def self.search(search,content)
    if search == "forward_match"
      @user = User.where("name LIKE?", "#{content}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{content}")
    elsif search == "perfect_match"
      @user = User.where("#{content}")
    elsif search == "pertical_match"
      @user = User.where("name LIKE?", "%#{content}%")
    else
      @user = User.all
    end
  end
=======

>>>>>>> origin/master
end

app/controllers/users_controller.rb
<<<<<<< HEAD

=======
>>>>>>> origin/master
class UsersController < ApplicationController

before_action :authenticate_user!

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@hon = Book.new
  end

  def edit
  	@user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
  	  redirect_to user_path(@user.id)
    else render action: :edit
    end
  end

  def index
  	@users = User.all
    @user = current_user
    @hon = Book.new
  end

  private
  def user_params
  	params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
      <% users.each do |user| %>
      <tbody>
      <tr>
        <td><%= attachment_image_tag user,:profile_image, :fill,30,30, format: 'jpeg',fallback: "no_image.jpg",size:'60x60' %></td>
        <td><%= user.name %></td>
        <td>
          <%= render 'relationships/follow_button', user:user %>
        </td>
        <td><%= link_to 'Show', user_path(user.id) %></td>
        <% end %>
      </tr>
    </tbody>

app/views/users/_profile.html.erb
      <h2>User info</h2>
      <table class="table">
        <tr><%= attachment_image_tag user, :profile_image, :fill,60,60, format:'jpeg',fallback: "no_image.jpg" %></tr>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
      </table>

        <div class="row">
        <%= link_to "", edit_user_path(user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>
      </div>

app/views/users/edit.html.erb
<div class='container'>

<h2>User info</h2>

<%= form_for(@user) do |f| %>

<% if @user.errors.any? %>
  <div id="error_explanation">
     <h2><%= @user.errors.count %>error prohibited this book from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

	<h4>name</h4>
	<%=f.text_field :name %>
	<h4>image</h4>
    <%=f.attachment_field :profile_image %>

    <h4>introduction</h4>
    <%=f.text_area :introduction %>

    <%= f.submit 'Update User' %>

    <%end%>
  </div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
<<<<<<< HEAD

<%= render 'profile', user:current_user %>
<%= render 'books/newbook', book:@hon %>
=======
      <h2>User info</h2>
      <table class="table">
        <tr><%= attachment_image_tag current_user, :profile_image, :fill,60,60, format:'jpeg',fallback: "no_image.jpg" %></tr>
        <tr>
          <th>name</th>
          <th><%= current_user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= current_user.introduction %></th>
        </tr>
      </table>

        <div class="row">
        <%= link_to "", edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>
      </div>



      <h2>New book</h2>
         <%= form_for(@hon) do |f| %>
            <% if @hon.errors.any? %>
              <div id="error_explanation" class="alert alert-danger">
              <p><%= @hon.errors.count %>error prohibited this book from being saved:</p>
              <ul>
              <% @hon.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
              </ul>
              </div>
            <% end %>

      <div class="field row">
      <label for="book_opinion">Title</label>
      <%= f.text_field :title, class:"col-xs-12" %>
    </div>

      <div class="field row">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body, class:"col-xs-12" %>
    </div>

<br/>
      <div class="actions row">
      <%= f.submit('Create Book',class:"btn btn-primary col-xs-12") %>
      </div>
      <% end %>
    </div>
>>>>>>> origin/master

      <div class="col-xs-9">
      <h2>Users</h2>

<<<<<<< HEAD
   <table class='table'>
    <thead>
=======
      <table class='table'>
        <thead>
>>>>>>> origin/master
       <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
<<<<<<< HEAD
       </tr>
    </thead>

<%= render 'index', users: @users %>

=======
      </tr>
    </thead>

      <% @users.each do |user| %>
      <tbody>
      <tr>
        <td><%= attachment_image_tag user,:profile_image, :fill,30,30, format: 'jpeg',fallback: "no_image.jpg",size:'60x60' %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user.id) %></td>
        <% end %>
      </tr>
    </tbody>
>>>>>>> origin/master
    </table>
  </div>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
<<<<<<< HEAD

<%= render 'profile', user:current_user %>
<%= render 'books/newbook', book:@hon %>
=======
      <h2>User info</h2>
      <table class="table">
        <tr><%= attachment_image_tag current_user, :profile_image, :fill,60,60, format:'jpeg',fallback: "no_image.jpg" %></tr>
        <tr>
          <th>name</th>
          <th><%= current_user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= current_user.introduction %></th>
        </tr>
      </table>

        <div class="row">
        <%= link_to "", edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>
      </div>



      <h2>New book</h2>
         <%= form_for(@hon) do |f| %>
            <% if @hon.errors.any? %>
              <div id="error_explanation" class="alert alert-danger">
              <p><%= @hon.errors.count %>error prohibited this book from being saved:</p>
              <ul>
              <% @hon.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
              </ul>
              </div>
            <% end %>

      <div class="field row">
      <label for="book_opinion">Title</label>
      <%= f.text_field :title, class:"col-xs-12" %>
    </div>

      <div class="field row">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body, class:"col-xs-12" %>
    </div>

<br/>
      <div class="actions row">
      <%= f.submit('Create Book',class:"btn btn-primary col-xs-12") %>
      </div>
      <% end %>
    </div>
>>>>>>> origin/master


    <div class="col-xs-9">

      <h2>Books</h2>

      <table class='table table-hover table-inverse'>
        <thead>
       <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
<<<<<<< HEAD
        <th></th>
=======
>>>>>>> origin/master
      </tr>
    </thead>

      <% @books.each do |book| %>
      <tbody>
      <tr>
      <td><%= attachment_image_tag @user, :profile_image, :fill,60,60, format:'jpeg',fallback: "no_image.jpg",:size=>'60x60' %></td>
        <td><%=link_to book_path(book.id) do %>
          <%= book.title %>
          <% end %>
        </td>
        <td><%= book.body %></td>

<<<<<<< HEAD
        <td>
            コメント数：<%= book.book_comments.count %>
        </td>

=======
>>>>>>> origin/master
        <% end %>
      </tr>
    </tbody>
    </table>
  </div>
</div>
</div>
</div>