config/routes.rb
Rails.application.routes.draw do

  get "home/about" => "homes#show"
  root to: 'homes#index'
  devise_for :users
<<<<<<< HEAD
  resources :users, only:[:show, :edit, :update, :index] do
    get 'following' => 'relationships#following'
    get 'followed' => 'relationships#followed'
  end



  resources :books do
  	resource :favorites, only:[:create, :destroy]
  	resources :book_comments, only:[:create, :destroy]
  end

  resources :relationships, only:[:create, :destroy]

  get '/search' => 'searches#search'
=======
  resources :books
  resources :users, only:[:show, :edit, :update, :index]
>>>>>>> origin/master
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	validates :body, length:{maximum:200}
    validates :body, presence: true
    validates :title, presence: true
<<<<<<< HEAD

    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy

    def favorited_by?(user)
    	favorites.where(user_id: user.id).exists?
    end

    #@book.favorited_by?(current_user)

    def self.search(search,content)
        if search == "forward_match"
            @book = Book.where("title LIKE?", "#{content}%")
        elsif search == "backward_match"
            @book = Book.where("title LIKE?", "%#{content}")
        elsif search == "perfect_match"
            @book = Book.where("#{content}")
        elsif search == "pertial_match"
            @book = Book.where("title LIKE?", "%#{content}%")
        else
            @book = Book.all
        end
    end
=======
>>>>>>> origin/master
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :authenticate_user!
before_action :correct_user, only:[:edit, :update]

	def new
		@hon = Book.new
	end

	def create
		@hon = Book.new(book_params)
		@hon.user_id = current_user.id
		@books = Book.all
		if @hon.save
			flash[:notice] = "Book was successfully created"
		    redirect_to book_path(@hon.id)
		else
			render :index
		end
	end

	def show
		@hon = Book.new
		@book = Book.find(params[:id])
<<<<<<< HEAD
		@user = @book.user
		@book_comment = BookComment.new
		@book_comments = BookComment.all
=======
		@user = current_user
>>>>>>> origin/master
	end

	def update
		@book =Book.find(params[:id])
		if @book.update(book_params)
			flash[:notice] = "Book was successfully created"
		    redirect_to book_path(@book.id)
        else render action: :edit
        end
	end

	def index
		@books = Book.all
		@hon = Book.new

	end

	def edit
		@book = Book.find(params[:id])
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to book_path
	end

private
def book_params
	params.require(:book).permit(:title, :body, :user)
end

def correct_user
    @user = current_user.books.find_by(id: params[:id])
    unless @user
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_detail.html.erb
<table class='table table-hover table-inverse'>

    <tr>
     <th><%= attachment_image_tag book.user, :profile_image, :fill,60,60, format:'jpeg',fallback: "no_image.jpg",:size=>'60x60' %>
      <br/>
      <%= link_to user_path(book.user) do %>
      <%= book.user.name %>
      <% end %>
    </th>
    <th><%= book.title %></th>
    <th><%= book.body %></th>


    <% if book.user == current_user %>
    <th><%=link_to "Edit", edit_book_path(book.id),class:"btn btn-success" %></th>
    <th><%= link_to "Destroy", book_path(book.id),class:"btn btn-danger", method: :delete, date:{confirm:'削除しますか？'} %></th>

    <% end %>

        <td class= "book_<%=book.id %>">
          <%= render 'favorites/favorite', book: book %>
        </td>


  </tr>
</table>

app/views/books/_index.html.erb
      <table class='table table-hover table-inverse'>
       <thead>
         <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
          <th></th>
          <th>
         </tr>
        </thead>

        <tbody>
         <% books.each do |book| %>
          <tr>
           <td>
            <%= link_to user_path(book.user) do %>
             <%= attachment_image_tag book.user, :profile_image, :fill,60,60, format:'jpeg',fallback: "no_image.jpg",:size=>'60x60' %>
            <% end %>
           </td>
           <td>
            <%=link_to book_path(book.id) do %>
            <%= book.title %>
            <% end %>
           </td>
           <td>
            <%= book.body %>
           </td>

          <td class= "book_<%=book.id %>">
          <%= render 'favorites/favorite', book:book %>
          </td>

          <td>
            コメント数：<%= book.book_comments.count %>
          </td>

          <% end %>
        </tr>
      </tbody>
    </table>

app/views/books/_newbook.html.erb
      <h2>New book</h2>
         <%= form_for(@hon) do |f| %>
            <% if @hon.errors.any? %>
              <div id="error_explanation" class="alert alert-danger">
              <p><%= @hon.errors.count %>error prohibited this book from being saved:</p>
              <ul>
              <% @hon.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
              </ul>
              </div>
            <% end %>

      <div class="field row">
      <label for="book_opinion">Title</label>
      <%= f.text_field :title, class:"col-xs-12" %>
    </div>

      <div class="field row">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body, class:"col-xs-12" %>
    </div>

<br/>
      <div class="actions row">
      <%= f.submit('Create Book',class:"btn btn-primary col-xs-12") %>
      </div>
      <% end %>
    </div>

app/views/books/edit.html.erb
<div class='container'>

<div class='row'>

<h1>Editing Book</h1>

<%= form_for (@book) do |f| %>


<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @book.errors.count %>error prohibited this book from being saved:</h2>

    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


	<h4>Title</h4>
	<%= f.text_field :title %>

	<h4>Opinion</h4>
	<%= f.text_area :body %>

	<%= f.submit 'Update Book' %>

<% end %>

<%= link_to "Show", book_path(@book.id) %>

<%= link_to "Back",books_path %>

<<<<<<< HEAD
=======
</div>
>>>>>>> origin/master
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
<<<<<<< HEAD

     <%= render 'users/profile', user:current_user %>
     <%= render 'newbook', book:@book %>


    <div class="col-xs-9">

     <h2>Books</h2>
      <%= render 'index', books:@books %>

    </div>
    </div>
  </div>
</div>
=======
      <h2>User info</h2>
      <table class="table">
        <tr><%= attachment_image_tag current_user, :profile_image, :fill,60,60, format:'jpeg',fallback: "no_image.jpg" %></tr>
        <tr>
          <th>name</th>
          <th><%= current_user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= current_user.introduction %></th>
        </tr>
      </table>

        <div class="row">
        <%= link_to "", edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>
      </div>



      <h2>New book</h2>
         <%= form_for(@hon) do |f| %>
            <% if @hon.errors.any? %>
              <div id="error_explanation" class="alert alert-danger">
              <p><%= @hon.errors.count %>error prohibited this book from being saved:</p>
              <ul>
              <% @hon.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
              </ul>
              </div>
            <% end %>

      <div class="field row">
      <label for="book_opinion">Title</label>
      <%= f.text_field :title, class:"col-xs-12" %>
    </div>

      <div class="field row">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body, class:"col-xs-12" %>
    </div>

<br/>
      <div class="actions row">
      <%= f.submit('Create Book',class:"btn btn-primary col-xs-12") %>
      </div>
      <% end %>
    </div>


    <div class="col-xs-9">
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>
       <thead>
       <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>

      <% @books.each do |book| %>
      <tbody>
      <tr>
       <td>
          <%= link_to user_path(book.user) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill,60,60, format:'jpeg',fallback: "no_image.jpg",:size=>'60x60' %>
          <% end %>
        </td>
        <td><%=link_to book_path(book.id) do %>
          <%= book.title %>
          <% end %>
        </td>
        <td><%= book.body %></td>

        <% end %>
      </tr>
    </tbody>
    </table>
  </div>
</div>
</div>
</div>
>>>>>>> origin/master


app/views/books/new.html.erb
<h1>New book</h1>
<%= form_for(@hon) do |f| %>
<% if @hon.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @hon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h4>Title</h4>
<%= f.text_field :title, :size=>"28"%>

<h4>Opinion</h4>
<%= f.text_area :body, :size=>"30" %>

<%= f.submit('Create Book',class: 'btn btn-primary') %>
<% end %>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
<<<<<<< HEAD
     <%= render 'users/profile', user:@user %>
     <%= render 'newbook',book:@book %>

    <div class="col-xs-9">
     <h2>Book detail</h2>
      <%= render 'detail', book:@book %>

     <%=form_for [@book, @book_comment] do |f| %>
      <%=f.text_area :comment %>
      <%=f.submit "送信する" %>
     <% end %>

     <h4>コメント一覧</h4>
      コメント数：<%= @book.book_comments.count %>

      <% @book.book_comments.each do |book_comment| %>
       <%= book_comment.comment %>

       <% if book_comment.user ==  current_user %>
        <%= link_to "削除", book_book_comment_path(@book.id,book_comment.id),method: :delete %>
       <% end %>

      <% end %>
    </div>
    </div>
  </div>
</div>
=======
      <h2>User info</h2>
      <table class="table">
        <tr><%= attachment_image_tag current_user, :profile_image, :fill,60,60, format:'jpeg',fallback: "no_image.jpg" %></tr>
        <tr>
          <th>name</th>
          <th><%= current_user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= current_user.introduction %></th>
        </tr>
      </table>

        <div class="row">
        <%= link_to "", edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>
      </div>



      <h2>New book</h2>
         <%= form_for(@hon) do |f| %>
            <% if @hon.errors.any? %>
              <div id="error_explanation" class="alert alert-danger">
              <p><%= @hon.errors.count %>error prohibited this book from being saved:</p>
              <ul>
              <% @hon.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
              </ul>
              </div>
            <% end %>

      <div class="field row">
      <label for="book_opinion">Title</label>
      <%= f.text_field :title, class:"col-xs-12" %>
    </div>

      <div class="field row">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body, class:"col-xs-12" %>
    </div>

<br/>
      <div class="actions row">
      <%= f.submit('Create Book',class:"btn btn-primary col-xs-12") %>
      </div>
      <% end %>
    </div>

  <div class="col-xs-9">
   <h2>Book detail</h2>

   <table class='table table-hover table-inverse'>

    <tr>
     <th><%= attachment_image_tag @book.user, :profile_image, :fill,60,60, format:'jpeg',fallback: "no_image.jpg",:size=>'60x60' %>
      <br/>
      <%= link_to user_path(@book.user) do %>
      <%= @book.user.name %>
      <% end %>
    </th>
    <th><%= @book.title %></th>
    <th><%= @book.body %></th>


    <% if @book.user == current_user %>
    <th><%=link_to "Edit", edit_book_path(@book.id),class:"btn btn-success" %></th>
    <th><%= link_to "Destroy", book_path(@book.id),class:"btn btn-danger", method: :delete, date:{confirm:'削除しますか？'} %></th>
    <% end %>

  </tr>
</table>


</div>
</div>
</div>
>>>>>>> origin/master