config/routes.rb
Rails.application.routes.draw do

  get "home/about" => "homes#show"
  root to: 'homes#index'
  devise_for :users
<<<<<<< HEAD
  resources :users, only:[:show, :edit, :update, :index] do
    get 'following' => 'relationships#following'
    get 'followed' => 'relationships#followed'
  end



  resources :books do
  	resource :favorites, only:[:create, :destroy]
  	resources :book_comments, only:[:create, :destroy]
  end

  resources :relationships, only:[:create, :destroy]

  get '/search' => 'searches#search'
=======
  resources :books
  resources :users, only:[:show, :edit, :update, :index]
>>>>>>> origin/master
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	validates :body, length:{maximum:200}
    validates :body, presence: true
    validates :title, presence: true
<<<<<<< HEAD

    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy

    def favorited_by?(user)
    	favorites.where(user_id: user.id).exists?
    end

    #@book.favorited_by?(current_user)

    def self.search(search,content)
        if search == "forward_match"
            @book = Book.where("title LIKE?", "#{content}%")
        elsif search == "backward_match"
            @book = Book.where("title LIKE?", "%#{content}")
        elsif search == "perfect_match"
            @book = Book.where("#{content}")
        elsif search == "pertial_match"
            @book = Book.where("title LIKE?", "%#{content}%")
        else
            @book = Book.all
        end
    end
=======
>>>>>>> origin/master
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user
	belongs_to :follow, class_name: 'User' #followモデルじゃなくてuserモデルを参照

	validates :user_id, presence: true
	validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
<<<<<<< HEAD
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
=======
>>>>>>> origin/master
  attachment :profile_image

  validates :name, presence: true
  validates :name, length:{maximum:20}
  validates :name, length:{minimum:2}
  validates :introduction, length:{maximum:50}

<<<<<<< HEAD
  has_many :relationships, foreign_key: 'user_id'
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user) #フォローしているuserを持ってきてother_userがいないか確認
  end



  def self.search(search,content)
    if search == "forward_match"
      @user = User.where("name LIKE?", "#{content}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{content}")
    elsif search == "perfect_match"
      @user = User.where("#{content}")
    elsif search == "pertical_match"
      @user = User.where("name LIKE?", "%#{content}%")
    else
      @user = User.all
    end
  end
=======

>>>>>>> origin/master
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource)
	user_path(current_user.id)
end

def after_sign_up_path_for(resource)
	root_path
end

protected
def configure_permitted_parameters
	devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :authenticate_user!
before_action :correct_user, only:[:edit, :update]

	def new
		@hon = Book.new
	end

	def create
		@hon = Book.new(book_params)
		@hon.user_id = current_user.id
		@books = Book.all
		if @hon.save
			flash[:notice] = "Book was successfully created"
		    redirect_to book_path(@hon.id)
		else
			render :index
		end
	end

	def show
		@hon = Book.new
		@book = Book.find(params[:id])
<<<<<<< HEAD
		@user = @book.user
		@book_comment = BookComment.new
		@book_comments = BookComment.all
=======
		@user = current_user
>>>>>>> origin/master
	end

	def update
		@book =Book.find(params[:id])
		if @book.update(book_params)
			flash[:notice] = "Book was successfully created"
		    redirect_to book_path(@book.id)
        else render action: :edit
        end
	end

	def index
		@books = Book.all
		@hon = Book.new

	end

	def edit
		@book = Book.find(params[:id])
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to book_path
	end

private
def book_params
	params.require(:book).permit(:title, :body, :user)
end

def correct_user
    @user = current_user.books.find_by(id: params[:id])
    unless @user
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		@book = Book.find(params[:book_id])
		@favorite = @book.favorites.new(user_id: current_user.id)
		#@favorite.user_id = current_user.id
		#favorite = current_user.favorites.new(book_id: book.id)
		@favorite.save
	end

	def destroy
		@book = Book.find(params[:book_id])
		@favorite = Favorite.find_by(book_id: @book.id)
		@favorite.user_id = current_user.id
		#favorite = current_user.favorites.find_by(book_id: book.id)
		@favorite.destroy
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	before_action :authenticate_user!

 def search
  @content = params["kensaku"]["content"]
  @model = params["kensaku"]["model"]
  @search = params["kensaku"]["search"]
  @datas = search_for(@content, @model, @search)

  p @content
  p @model
  p @search
  p @datas
 end

 private

def search_for(model, content, method)
    if model == 'user'
      if method == 'perfect'
        User.where(name: content)
      elsif method == 'forward'
        User.where('name LIKE ?', content+'%')
      elsif method == 'backward'
        User.where('name LIKE ?', '%'+content)
      else
        User.where('name LIKE ?', '%'+content+'%')
      end
    elsif model == 'book'
      if method == 'perfect'
        Book.where(title: content)
      elsif method == 'forward'
        Book.where('title LIKE ?', content+'%')
      elsif method == 'backward'
        Book.where('title LIKE ?', '%'+content)
      else
        Book.where('title LIKE ?', '%'+content+'%')
      end
    end
  end


end

app/controllers/users_controller.rb
<<<<<<< HEAD

=======
>>>>>>> origin/master
class UsersController < ApplicationController

before_action :authenticate_user!

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@hon = Book.new
  end

  def edit
  	@user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
  	  redirect_to user_path(@user.id)
    else render action: :edit
    end
  end

  def index
  	@users = User.all
    @user = current_user
    @hon = Book.new
  end

  private
  def user_params
  	params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookers2</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav class='nav navbar-nab navbar-left'>
        <span style="color:white;font-size:20px">Bookers</span></nav>
      <nav>
        <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">

          <% if user_signed_in? %>
<<<<<<< HEAD

=======
>>>>>>> origin/master
          <li>
            <%= link_to "Home",user_path(current_user.id),class:"glyphicon glyphicon-home home" %>
          </li>
          <li>
          <%= link_to "Users",users_path,class:"glyphicon glyphicon-user" %>
          </li>
          <li>
            <%= link_to "Books", books_path,class:"glyphicon glyphicon-book" %>
          </li>
          <li>
            <%= link_to "logout", destroy_user_session_path,class:"glyphicon glyphicon-share", method: :delete %>
          </li>

<<<<<<< HEAD
          <%= form_tag(search_path,:method => 'get') do %>
           <%= text_field_tag 'kensaku[content]' %>
           <%= select_tag 'kensaku[model]', options_for_select([['User','user'],['Book','book']]) %>
           <%= select_tag 'kensaku[search]', options_for_select([["前方一致","forward"],["後方一致","backward"],["完全一致","perfect"],["部分一致","pertial"]]) %>
           <%= submit_tag 'Search', :name => nil %>
          <% end %>

=======
>>>>>>> origin/master
          <% else %>

          <li>
            <%= link_to "Home","/",class:"glyphicon glyphicon-home home" %>
          </li>

          <li class="">
            <%= link_to "About","home/about",class:"glyphicon glyphicon-link" %>
          </li>
          <li>
            <%= link_to "sign up",new_user_registration_path ,class:"glyphicon glyphicon-edit"%>
          </li>
          <li>
            <%= link_to "login", new_user_session_path,class:"glyphicon glyphicon-log-in" %>
          </li>
          <% end %>


        </ul>
      </nav>
    </div>
  </header>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<% flash.each do |key,value| %>
<%= content_tag(:div, value,class:"#key") %>
<% end %>


<<<<<<< HEAD
<%= yield %>
=======
  <%= yield %>
>>>>>>> origin/master

<footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRigth Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

</body>
</html>